Kit.Server/Controllers/KitPoolsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Kit.Server.Models;

namespace Kit.Server.Controllers
{
    public class KitPoolsController : Controller
    {
        private LabTypeKitDbContext db = new LabTypeKitDbContext();

        // GET: KitPools
        [HttpGet]
        public ActionResult Index()
        {
            var kpl = db.KitPools.ToList();
            return View(kpl);
        }

        // GET: KitPools/MyView/5
        [HttpGet]
        public ActionResult MyView(int? x)
        {
            var kpl = db.KitPools.ToList();
            return View(kpl);
        }

        // GET: KitPools/Details/5
        [HttpGet]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KitPool kitPool = db.KitPools.Find(id);
            if (kitPool == null)
            {
                return HttpNotFound();
            }
            return View(kitPool);
        }

        // GET: KitPools/Create
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        // POST: KitPools/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,KitName")] KitPool kitPool)
        {
            if (ModelState.IsValid)
            {
                db.KitPools.Add(kitPool);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(kitPool);
        }

        // GET: KitPools/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KitPool kitPool = db.KitPools.Find(id);
            if (kitPool == null)
            {
                return HttpNotFound();
            }
            return View(kitPool);
        }

        // POST: KitPools/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,KitName")] KitPool kitPool)
        {
            if (ModelState.IsValid)
            {
                db.Entry(kitPool).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(kitPool);
        }

        // GET: KitPools/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KitPool kitPool = db.KitPools.Find(id);
            if (kitPool == null)
            {
                return HttpNotFound();
            }
            return View(kitPool);
        }

        // POST: KitPools/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            KitPool kitPool = db.KitPools.Find(id);
            db.KitPools.Remove(kitPool);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: KitPools/BeadDetail/5
        [HttpGet]
        public ActionResult BeadDetail(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var pools = db.KitPools.ToList();

            foreach (var kitpool in pools)
            {
                var conjugations = kitpool.KitConjugations.ToList();
                var conjugation = conjugations.Find(c => c.Id == id);
                if (conjugation != null)
                {
                    var bead = conjugation.Bead;
                    var pool = new KitPool() {Id = kitpool.Id,KitName=kitpool.KitName,KitConjugations = new List<KitConjugation>(kitpool.KitConjugations.Where(kp=>kp.Bead==bead))};
                    return View(pool);
                }
            }
            
                return HttpNotFound();
            


            //var kitconjugations = db.KitPools.Select(kc => kc.KitConjugations).ToList();
            //KitConjugation conjugation = null;
            //foreach (var kitconjugation in kitconjugations)
            //{
            //    conjugation = kitconjugation.Find(c => c.Id == id);
            //    if (conjugation != null) break;
            //}

            //if (conjugation == null)
            //{
            //    return HttpNotFound();
            //}
            //return View();
        }



        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Kit.Server/Views/KitPools/BeadDetail.cshtml
@using System.Globalization
@model Kit.Server.Models.KitPool


@{
    ViewBag.Title = "BeadDetail";
}

<h2>Bead Details</h2>

<div>
    <p>Bead Details</p>
    <table class="col-md-4">
        <tr>
            <th>Bead</th>
            <th>Probe</th>
        </tr>
        @{ var c = Model.KitConjugations;
         string displaybead = "";}

        @foreach (var item in Model.KitConjugations)
        {
            <tr>
                <td>
                    @Html.ActionLink(item.Bead.ToString(CultureInfo.InvariantCulture), "BeadDetail", new { id = item.Id })
                <td>
                    <div class="dynamicbar txt-color-greenDark hidden-mobile hidden-md hidden-sm"><i class="fa fa-spinner fa-spin"></i></div>
                </td>

                <td>
                    @Html.ActionLink(item.ProbeName, "index", new { id = item.Id })
                </td>


                <td>
                    @Html.ActionLink("Troubleshoot", "index", new { id = item.Id }) |
                    @Html.ActionLink("Confirm", "index", new { id = item.Id }) |
                    @Html.ActionLink("Specificity", "index", new { id = item.Id })
                </td>
            </tr>
        }
    </table>
</div>

Kit.Server/Views/KitPools/Create.cshtml
@model Kit.Server.Models.KitPool

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>KitPool</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.KitName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.KitName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.KitName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Kit.Server/Views/KitPools/Delete.cshtml
@model Kit.Server.Models.KitPool

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>KitPool</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.KitName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KitName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Kit.Server/Views/KitPools/Details.cshtml
@using Kit.Server.Models
@model Kit.Server.Models.KitPool

@{
    ViewBag.Title = "Details";
}
<style type="text/css">
    .dynamicsparkline {
    }
</style>

<h2>Details</h2>

<div>
    <h4>KitPool</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt class="col-md-3">
            @Html.DisplayNameFor(model => model.KitName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.KitName)
        </dd>
    </dl>
</div>

<div>
    <p>Kit Conjugations</p>
    <table class="col-md-4">
        <tr>
            <th>Bead</th>
            <th>Probe</th>
        </tr>
        @{ var bead = -1;
         string displaybead = "";}

        @foreach (var item in Model.KitConjugations)
        {
            <tr>
                <td>
                    @{var conjugation = item;}
                    @{if (conjugation.Bead != bead)
                        {
                            bead = conjugation.Bead;
                            @Html.ActionLink(bead.ToString(), "index", new { id = item.Id })
                        }
                    }
                </td>
                <td>
                    <div class="dynamicbar txt-color-greenDark hidden-mobile hidden-md hidden-sm"><i class="fa fa-spinner fa-spin"></i></div>
                </td>

                <td>
                    @Html.ActionLink(conjugation.ProbeName, "index", new { id = item.Id })
                </td>


                <td>
                    @Html.ActionLink("Edit", "index", new { id = item.Id }) |
                    @Html.ActionLink("Details", "index", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "index", new { id = item.Id })
                </td>
            </tr>
        }
    </table>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to " + Model.KitName, "Index")
</p>

Kit.Server/Views/KitPools/Edit.cshtml
@model Kit.Server.Models.KitPool

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>KitPool</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.KitName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.KitName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.KitName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Kit.Server/Views/KitPools/Index.cshtml
@model IEnumerable<Kit.Server.Models.KitPool>

@{
    ViewBag.Title = "LABType® SSO Typing Tests";
}

<div class="row">
    <div class="col-md-3">
        <h2>Development</h2>
        <p>Kits in development</p>
       


        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.KitName)
                </th>
                
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.ActionLink(item.KitName, "Details", new { id = item.Id })
                    </td>
                </tr>
            }

        </table>
    </div>


</div>




<h2>LABType</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

@* ----------------------------------------------CRAP-----------------------------------------------------------*@

@*<canvas id="barChartLoc" height="300" width="250"></canvas>

    <script>
        var barChartLocData = {
            labels: ["","","","",""],
            datasets: [{ fillColor: "yellow", strokeColor: "blue", data: [15, 20, 35, 12, 24] }]
        };
        var mybarChartLoc = new Chart(document.getElementById("barChartLoc").getContext("2d")).Bar(barChartLocData, { barValueSpacing: 10 });

            </script>*@

@*<p><a class="btn btn-default" href="@Url.Action("Index","KitPools")">Simple Kits &raquo;</a></p>*@

Kit.Server/Views/KitPools/MyView.cshtml
@model IEnumerable<Kit.Server.Models.KitPool>


@{
    ViewBag.Title = "Project Pools";
}


@{
    var kitname = Model.FirstOrDefault().KitName;
    kitname = kitname.Substring(0, kitname.IndexOf('-'));

}


<h2>Active Project Pools for @kitname</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

@Html.JQueryUI().Button("Upload Poolsheet", ButtonElement.Button, ButtonType.Button, null)

<h2>@Html.DisplayNameFor(model => model.KitName)</h2>
<ul id="sortable">
    @foreach (var item in Model)
    {
        //<li> @Html.DisplayFor(modelItem => item.KitName) </li>
        <li> @Html.ActionLink(item.KitName, "Details", new { id = item.Id })</li>
    }
</ul>


@section Scripts {
    <script>
    $(function () {
        $("#sortable").sortable();
        $("#sortable").disableSelection();
    });
    </script>

}

@*--------------CRAP ----------------------

    <script>
        $(function () {
            $("#sortable2").sortable();
            $("#sortable2").disableSelection();
        });
    </script>
            @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.KitName)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }*@